services:
  db:
    image: postgres:16
    container_name: HYMB_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:  
      - ${DB_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/ddl/01_create_tables.sql:/docker-entrypoint-initdb.d/01_create_tables.sql
      - ./sql/dml/02_insert_data.sql:/docker-entrypoint-initdb.d/02_insert_data.sql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: HYMB_backend
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./backend:/app
      - ./sql:/sql
    ports:
      - "8000:8000"

    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 5s
      timeout: 5s
      retries: 5
    
    depends_on:
      db:
        condition: service_healthy


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: HYMB_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - API_URL_INTERNAL=http://backend:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      backend:
        condition: service_healthy

volumes:
  postgres_data: