"""Cria schema do hospital via ORM

Revision ID: 93b1444b14a9
Revises: 
Create Date: 2026-07-31 02:59:54.466056
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '93b1444b14a9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alergia',
    sa.Column('id_alergia', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_alergia', name='alergia_pkey'),
    sa.UniqueConstraint('nome', name='alergia_nome_key')
    )
    op.create_table('pessoa',
    sa.Column('id_pessoa', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('is_flamengo', sa.Boolean(), nullable=False),
    sa.Column('telefone', sa.String(length=15), nullable=True),
    sa.CheckConstraint("cpf::text ~ '^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$'::text", name='pessoa_cpf_check'),
    sa.CheckConstraint("data_nascimento >= '1900-01-01'::date AND data_nascimento <= CURRENT_DATE", name='pessoa_data_nascimento_check'),
    sa.CheckConstraint("telefone::text ~ '^\\(\\d{2}\\) \\d{5}-\\d{4}$'::text", name='pessoa_telefone_check'),
    sa.PrimaryKeyConstraint('id_pessoa', name='pessoa_pkey'),
    sa.UniqueConstraint('cpf', name='pessoa_cpf_key')
    )
    op.create_table('procedimento',
    sa.Column('id_procedimento', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('tempo_medio_minutos', sa.Integer(), nullable=False),
    sa.Column('nivel_risco', sa.String(length=20), server_default=sa.text("'BAIXO'::character varying"), nullable=True),
    sa.CheckConstraint("nivel_risco::text = ANY (ARRAY['BAIXO'::character varying, 'MEDIO'::character varying, 'ALTO'::character varying]::text[])", name='procedimento_nivel_risco_check'),
    sa.CheckConstraint('tempo_medio_minutos > 0', name='procedimento_tempo_medio_minutos_check'),
    sa.PrimaryKeyConstraint('id_procedimento', name='procedimento_pkey'),
    sa.UniqueConstraint('codigo', name='procedimento_codigo_key')
    )
    op.create_table('unidade',
    sa.Column('id_unidade', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('capacidade_leitos', sa.Integer(), nullable=False),
    sa.CheckConstraint('capacidade_leitos >= 0', name='unidade_capacidade_leitos_check'),
    sa.PrimaryKeyConstraint('id_unidade', name='unidade_pkey')
    )
    op.create_table('paciente',
    sa.Column('id_pessoa', sa.Integer(), nullable=False),
    sa.Column('num_convenio', sa.String(length=50), nullable=True),
    sa.Column('grupo_sanguineo', sa.String(length=3), nullable=True),
    sa.CheckConstraint("grupo_sanguineo::text = ANY (ARRAY['A+'::character varying, 'A-'::character varying, 'B+'::character varying, 'B-'::character varying, 'AB+'::character varying, 'AB-'::character varying, 'O+'::character varying, 'O-'::character varying]::text[])", name='paciente_grupo_sanguineo_check'),
    sa.ForeignKeyConstraint(['id_pessoa'], ['pessoa.id_pessoa'], name='paciente_id_pessoa_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_pessoa', name='paciente_pkey')
    )
    op.create_table('profissional',
    sa.Column('id_pessoa', sa.Integer(), nullable=False),
    sa.Column('crm', sa.String(length=20), nullable=False),
    sa.Column('data_admissao', sa.Date(), nullable=False),
    sa.Column('especialidade', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id_pessoa'], ['pessoa.id_pessoa'], name='profissional_id_pessoa_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_pessoa', name='profissional_pkey'),
    sa.UniqueConstraint('crm', name='profissional_crm_key')
    )
    op.create_table('internacao',
    sa.Column('id_internacao', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('id_unidade', sa.Integer(), nullable=False),
    sa.Column('data_hora_entrada', sa.DateTime(), nullable=False),
    sa.Column('data_hora_saida', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_paciente'], ['paciente.id_pessoa'], name='internacao_id_paciente_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_unidade'], ['unidade.id_unidade'], name='internacao_id_unidade_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_internacao', name='internacao_pkey')
    )
    op.create_table('paciente_alergia',
    sa.Column('id_pessoa', sa.Integer(), nullable=False),
    sa.Column('id_alergia', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_alergia'], ['alergia.id_alergia'], name='paciente_alergia_id_alergia_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_pessoa'], ['paciente.id_pessoa'], name='paciente_alergia_id_pessoa_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_pessoa', 'id_alergia', name='paciente_alergia_pkey')
    )
    op.create_table('preceptor',
    sa.Column('id_profissional', sa.Integer(), nullable=False),
    sa.Column('titulacao', sa.String(length=50), nullable=False),
    sa.Column('supervisao_ativa', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['id_profissional'], ['profissional.id_pessoa'], name='preceptor_id_profissional_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_profissional', name='preceptor_pkey')
    )
    op.create_table('residente',
    sa.Column('id_profissional', sa.Integer(), nullable=False),
    sa.Column('ano_residencia', sa.String(length=2), nullable=True),
    sa.CheckConstraint("ano_residencia::text = ANY (ARRAY['R1'::character varying, 'R2'::character varying, 'R3'::character varying]::text[])", name='residente_ano_residencia_check'),
    sa.ForeignKeyConstraint(['id_profissional'], ['profissional.id_pessoa'], name='residente_id_profissional_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_profissional', name='residente_pkey')
    )
    op.create_table('atendimento',
    sa.Column('id_atendimento', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('duracao_minutos', sa.Integer(), nullable=False),
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('id_residente', sa.Integer(), nullable=False),
    sa.Column('id_preceptor', sa.Integer(), nullable=False),
    sa.CheckConstraint('duracao_minutos > 0', name='atendimento_duracao_minutos_check'),
    sa.ForeignKeyConstraint(['id_paciente'], ['paciente.id_pessoa'], name='atendimento_id_paciente_fkey'),
    sa.ForeignKeyConstraint(['id_preceptor'], ['preceptor.id_profissional'], name='atendimento_id_preceptor_fkey'),
    sa.ForeignKeyConstraint(['id_residente'], ['residente.id_profissional'], name='atendimento_id_residente_fkey'),
    sa.PrimaryKeyConstraint('id_atendimento', name='atendimento_pkey')
    )
    op.create_table('escala',
    sa.Column('id_escala', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_unidade', sa.Integer(), nullable=False),
    sa.Column('id_residente', sa.Integer(), nullable=False),
    sa.Column('id_preceptor', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.String(length=15), nullable=True),
    sa.Column('turno', sa.String(length=10), nullable=True),
    sa.CheckConstraint("dia_semana::text = ANY (ARRAY['Segunda'::character varying, 'Terca'::character varying, 'Quarta'::character varying, 'Quinta'::character varying, 'Sexta'::character varying, 'Sabado'::character varying, 'Domingo'::character varying]::text[])", name='escala_dia_semana_check'),
    sa.CheckConstraint("turno::text = ANY (ARRAY['Manha'::character varying, 'Tarde'::character varying, 'Noite'::character varying]::text[])", name='escala_turno_check'),
    sa.ForeignKeyConstraint(['id_preceptor'], ['preceptor.id_profissional'], name='escala_id_preceptor_fkey'),
    sa.ForeignKeyConstraint(['id_residente'], ['residente.id_profissional'], name='escala_id_residente_fkey'),
    sa.ForeignKeyConstraint(['id_unidade'], ['unidade.id_unidade'], name='escala_id_unidade_fkey'),
    sa.PrimaryKeyConstraint('id_escala', name='escala_pkey'),
    sa.UniqueConstraint('id_unidade', 'dia_semana', 'turno', 'id_residente', name='unique_escala_residente')
    )
    op.create_table('procedimento_realizado',
    sa.Column('id_atendimento', sa.Integer(), nullable=False),
    sa.Column('id_procedimento', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('tempo_real_minutos', sa.Integer(), nullable=False),
    sa.Column('faturado', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.CheckConstraint('quantidade > 0', name='procedimento_realizado_quantidade_check'),
    sa.CheckConstraint('tempo_real_minutos > 0', name='procedimento_realizado_tempo_real_minutos_check'),
    sa.ForeignKeyConstraint(['id_atendimento'], ['atendimento.id_atendimento'], name='procedimento_realizado_id_atendimento_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_procedimento'], ['procedimento.id_procedimento'], name='procedimento_realizado_id_procedimento_fkey'),
    sa.PrimaryKeyConstraint('id_atendimento', 'id_procedimento', name='procedimento_realizado_pkey')
    )
    op.execute("""
        CREATE VIEW vw_pacientes_internados AS
        SELECT
            pe.nome AS paciente_nome,
            i.data_hora_entrada,
            u.nome AS unidade_internacao
        FROM paciente p
        JOIN pessoa pe ON p.id_pessoa = pe.id_pessoa
        JOIN internacao i ON p.id_pessoa = i.id_paciente
        JOIN unidade u ON i.id_unidade = u.id_unidade
        WHERE i.data_hora_saida IS NULL
          AND i.id_internacao = (
              SELECT i2.id_internacao
              FROM internacao i2
              WHERE i2.id_paciente = p.id_pessoa
              ORDER BY i2.data_hora_entrada DESC
              LIMIT 1
          )
    """)
    op.execute("""
        CREATE VIEW vw_residentes_sem_supervisor AS
        SELECT DISTINCT
            pe_res.nome AS residente_nome,
            pe_prec.nome AS preceptor_nome,
            pr.titulacao AS preceptor_titulacao,
            pr.supervisao_ativa
        FROM residente r
        JOIN pessoa pe_res ON r.id_profissional = pe_res.id_pessoa
        JOIN escala e ON r.id_profissional = e.id_residente
        JOIN preceptor pr ON e.id_preceptor = pr.id_profissional
        JOIN pessoa pe_prec ON pr.id_profissional = pe_prec.id_pessoa
        WHERE pr.titulacao != 'Doutor'
           OR pr.supervisao_ativa = FALSE
    """)
    op.execute("""
        CREATE VIEW vw_estatisticas_atendimentos_mensal AS
        WITH atendimento_unidade AS (
            SELECT
                a.id_atendimento,
                a.data_hora,
                a.duracao_minutos,
                TO_CHAR(a.data_hora, 'YYYY-MM') AS mes,
                e.id_unidade
            FROM atendimento a
            LEFT JOIN escala e
              ON a.id_residente = e.id_residente
             AND a.id_preceptor = e.id_preceptor
             AND CASE EXTRACT(ISODOW FROM a.data_hora)
                    WHEN 1 THEN 'Segunda'
                    WHEN 2 THEN 'Terca'
                    WHEN 3 THEN 'Quarta'
                    WHEN 4 THEN 'Quinta'
                    WHEN 5 THEN 'Sexta'
                    WHEN 6 THEN 'Sabado'
                    WHEN 7 THEN 'Domingo'
                 END = e.dia_semana
        )
        SELECT
            au.mes,
            u.nome AS unidade,
            COUNT(DISTINCT au.id_atendimento) AS total_atendimentos,
            ROUND(AVG(au.duracao_minutos), 2) AS media_duracao,
            MODE() WITHIN GROUP (ORDER BY p.nome) AS procedimento_mais_comum
        FROM atendimento_unidade au
        LEFT JOIN unidade u ON au.id_unidade = u.id_unidade
        LEFT JOIN procedimento_realizado pr
          ON au.id_atendimento = pr.id_atendimento
        LEFT JOIN procedimento p ON pr.id_procedimento = p.id_procedimento
        GROUP BY au.mes, u.nome
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP VIEW IF EXISTS vw_estatisticas_atendimentos_mensal')
    op.execute('DROP VIEW IF EXISTS vw_residentes_sem_supervisor')
    op.execute('DROP VIEW IF EXISTS vw_pacientes_internados')
    op.drop_table('procedimento_realizado')
    op.drop_table('escala')
    op.drop_table('atendimento')
    op.drop_table('residente')
    op.drop_table('preceptor')
    op.drop_table('paciente_alergia')
    op.drop_table('internacao')
    op.drop_table('profissional')
    op.drop_table('paciente')
    op.drop_table('unidade')
    op.drop_table('procedimento')
    op.drop_table('pessoa')
    op.drop_table('alergia')
    # ### end Alembic commands ###
