-- Triggers do projeto hospitalar.
-- PostgreSQL 16+

BEGIN;

-- Dependencias dos triggers.
ALTER TABLE procedimento
    ADD COLUMN IF NOT EXISTS media_tempo_procedimento NUMERIC(10, 2);

CREATE TABLE IF NOT EXISTS auditoria_atendimento (
    id_auditoria INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_atendimento INTEGER NOT NULL,
    operacao VARCHAR(10) NOT NULL,
    usuario VARCHAR(255) NOT NULL,
    dados_antigos JSONB,
    dados_novos JSONB,
    data_hora TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT auditoria_atendimento_pkey PRIMARY KEY (id_auditoria)
);

CREATE INDEX IF NOT EXISTS ix_auditoria_atendimento_id_atendimento
    ON auditoria_atendimento (id_atendimento);

-- Impede que um residente seja escalado no mesmo dia e turno
-- em unidades diferentes.
CREATE OR REPLACE FUNCTION fn_check_sobreposicao_escala()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM 1
    FROM residente r
    WHERE r.id_profissional = NEW.id_residente
    FOR UPDATE;

    IF EXISTS (
        SELECT 1
        FROM escala e
        WHERE e.id_residente = NEW.id_residente
          AND e.dia_semana = NEW.dia_semana
          AND e.turno = NEW.turno
          AND e.id_unidade <> NEW.id_unidade
          AND e.id_escala <> COALESCE(NEW.id_escala, -1)
    ) THEN
        RAISE EXCEPTION
            'Residente % ja esta escalado no dia % e turno % em outra unidade.',
            NEW.id_residente,
            NEW.dia_semana,
            NEW.turno
            USING ERRCODE = 'unique_violation';
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_check_sobreposicao_escala ON escala;

CREATE TRIGGER trg_check_sobreposicao_escala
BEFORE INSERT OR UPDATE ON escala
FOR EACH ROW
EXECUTE FUNCTION fn_check_sobreposicao_escala();

-- Audita inclusoes, alteracoes e exclusoes de atendimentos.
CREATE OR REPLACE FUNCTION fn_audita_atendimento()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        INSERT INTO auditoria_atendimento (
            id_atendimento,
            operacao,
            usuario,
            dados_antigos,
            dados_novos
        )
        VALUES (
            NEW.id_atendimento,
            TG_OP,
            CURRENT_USER,
            NULL,
            ROW_TO_JSON(NEW)
        );

        RETURN NEW;
    ELSIF TG_OP = 'UPDATE' THEN
        INSERT INTO auditoria_atendimento (
            id_atendimento,
            operacao,
            usuario,
            dados_antigos,
            dados_novos
        )
        VALUES (
            NEW.id_atendimento,
            TG_OP,
            CURRENT_USER,
            ROW_TO_JSON(OLD),
            ROW_TO_JSON(NEW)
        );

        RETURN NEW;
    ELSE
        INSERT INTO auditoria_atendimento (
            id_atendimento,
            operacao,
            usuario,
            dados_antigos,
            dados_novos
        )
        VALUES (
            OLD.id_atendimento,
            TG_OP,
            CURRENT_USER,
            ROW_TO_JSON(OLD),
            NULL
        );

        RETURN OLD;
    END IF;
END;
$$;

DROP TRIGGER IF EXISTS trg_audita_atendimento ON atendimento;

CREATE TRIGGER trg_audita_atendimento
AFTER INSERT OR UPDATE OR DELETE ON atendimento
FOR EACH ROW
EXECUTE FUNCTION fn_audita_atendimento();

-- Recalcula a media do tempo real do procedimento apos uma insercao.
CREATE OR REPLACE FUNCTION fn_atualiza_media_procedimentos()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE procedimento
    SET media_tempo_procedimento = (
        SELECT ROUND(AVG(pr.tempo_real_minutos), 2)
        FROM procedimento_realizado pr
        WHERE pr.id_procedimento = NEW.id_procedimento
    )
    WHERE id_procedimento = NEW.id_procedimento;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_atualiza_media_procedimentos
    ON procedimento_realizado;

CREATE TRIGGER trg_atualiza_media_procedimentos
AFTER INSERT ON procedimento_realizado
FOR EACH ROW
EXECUTE FUNCTION fn_atualiza_media_procedimentos();

COMMIT;
